version: "2"
services:
  test_api:
    image: test_api
    container_name: api
    build: ./api
    ports:
      - ${API_PORT}:3001
    volumes:
      - ./api:/app
      - v_api:/app/node_modules
    environment:
      - PORT=3001
      - NODE_ENV=${API_ENV}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASS=${REDIS_PASS}
      - REDIS_PORT=${REDIS_PORT}
  test_frontend:
    image: test_frontend
    container_name: frontend
    build: ./frontend
    ports:
      - ${FRONTEND_PORT}:3000
    volumes:
      - ./frontend/:/app
      - v_front:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
  redis-server:
    image: redis
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASS}
    volumes:
      - redis:/data
volumes:
  v_front:
  v_api:
  redis:
