version: "2"
services:
  test_api:
    image: test_api
    container_name: api
    build: ./api
    ports:
      - 8010:3001
    volumes:
      - ./api:/app
      - v_api:/app/node_modules
    environment:
      - PORT=3001
  test_frontend:
    image: test_frontend
    container_name: frontend
    build: ./frontend
    ports:
      - 80:3000
    volumes:
      - ./frontend/:/app
      - v_front:/app/node_modules
    environment:
      - API_PORT=8000
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
  redis-server:
    image: redis
    container_name: redis
    volumes:
      - redis:/data
volumes:
  v_front:
  v_api:
  redis:
